import React, { useRef } from 'react';
import styles from './FullReport.module.css';

const FullReport = ({ report }) => {
  const printRef = useRef(null);

  const handlePrint = () => {
    window.print();
  };

  if (!report) return null;

  return (
    <section className={styles.reportContainer}>
      <div className={styles.content}>
        <div className={styles.header}>
          <h2 className={styles.title}>Official Intelligence Document</h2>
          <button className={styles.printBtn} onClick={handlePrint}>
            Export PDF
          </button>
        </div>

        <div className={styles.documentBody} ref={printRef} id="printable-report">
          <div className={styles.docHeader}>
            <div className={styles.docBrand}>VERITAS</div>
            <div className={styles.docMeta}>
              <span>ID: {report.report_id || "V-0000"}</span>
              <span>Generated: {report.generated_at ? new Date(report.generated_at).toLocaleDateString() : new Date().toLocaleDateString()}</span>
            </div>
          </div>

          <h1 className={styles.docTitle}>{report.executive_brief?.headline || "Intelligence Report"}</h1>
          
          <div className={styles.docSection}>
            <h3 className={styles.sectionTitle}>I. Executive Brief</h3>
            <p className={styles.paragraph}>{report.executive_brief?.summary}</p>
          </div>

          <div className={styles.docSection}>
            <h3 className={styles.sectionTitle}>II. Key Findings</h3>
            <ul className={styles.list}>
              {report.key_insights?.map((insight, idx) => (
                <li key={idx} className={styles.listItem}>{insight}</li>
              ))}
            </ul>
          </div>

          <div className={styles.docSection}>
            <h3 className={styles.sectionTitle}>III. Risk Assessment</h3>
            <ul className={styles.list}>
              {report.risk_assessment?.map((risk, idx) => (
                <li key={idx} className={styles.listItem}>{risk}</li>
              ))}
            </ul>
          </div>

          <div className={styles.docSection}>
            <h3 className={styles.sectionTitle}>IV. Claim Intelligence</h3>
            {report.claim_intelligence?.top_claims?.map((c, idx) => (
              <div key={idx} className={styles.claimBlock}>
                <strong>Claim:</strong> {c.claim || c.text || c} <br />
                <strong>Evidence Strength:</strong> {c.evidence || c.evidence_strength || "Unknown"} <br />
                {c.why_it_matters && <span><strong>Impact:</strong> {c.why_it_matters}</span>}
              </div>
            ))}
          </div>

          <div className={styles.docSection}>
            <h3 className={styles.sectionTitle}>V. Uncertainty Analysis</h3>
            <ul className={styles.list}>
              {report.uncertainty_analysis?.map((item, idx) => (
                <li key={idx} className={styles.listItem}>{item}</li>
              ))}
            </ul>
          </div>

          <div className={styles.docSection}>
            <h3 className={styles.sectionTitle}>VI. Final Verdict</h3>
            <div className={styles.verdictBlock}>
              <strong>Classification:</strong> {report.final_verdict?.classification || report.final_verdict || "Unknown"} <br />
              <strong>Confidence:</strong> {report.final_verdict?.confidence ? `${report.final_verdict.confidence}%` : "N/A"} <br />
              <strong>Recommendation:</strong> {report.final_verdict?.recommendation || "Proceed with caution."}
            </div>
          </div>
          
          <div className={styles.docFooter}>
            Generated by VERITAS Autonomous Intelligence Engine v{report.report_version || "1.0"}
          </div>
        </div>
      </div>
    </section>
  );
};

export default FullReport;
